# Site settings
title: APS Distribution
email: help@apsdistribution.ca
description: > # this means to ignore newlines until "baseurl:"
  APS Distribution is the logistics partner in the GTA most dedicated to helping your businesses thrive. Specializing in warehouse storage, pick-and-pack, and third-party logistics (3PL) solutions for eCommerce, we offer a streamlined approach to managing inventory and fulfilling orders. Our goal is to take the complexity out of logistics so you can focus on growing your business.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username:
github_username: blakephillipsss

# Build settings
markdown: kramdown
